# Import thư viện PyTorch

In [1]:
import torch 
import torchvision
import torch.nn as nn
import numpy as np
import torchvision.transforms as transforms

# Mục lục

In [2]:
# ================================================================== #
#                             Mục lục                                #
# ================================================================== #
# 1. Ví dụ 1 về Autograd cơ bản
# 2. Ví dụ 2 về Autograd cơ bản
# 3. Tải dữ liệu từ Numpy
# 4. Input pipline 
# 5. Input pipline cho bộ dữ liệu tùy chọn (custom dataset)
# 6. Mô hình được huấn luyện từ trước (Pretrained model)
# 7. Lưu và tải lại mô hình (Save and load model)

# 1. Ví dụ 1 về Autograd cơ bản

In [3]:
# Khởi tạo các Tensor
x = torch.tensor(4., requires_grad=True)
w = torch.tensor(5., requires_grad=True)
b = torch.tensor(6., requires_grad=True)
# Lưu ý: đạt tham số requires_grad bằng True để cho phép tính Gradient

In [4]:
# Tạo ra một đồ thị tính toán (Computational Graph)
y = w * x + b # y = 4 * x + 6

In [5]:
# Tính Gradient
y.backward()

In [6]:
# In ra kết quả
print(x.grad)    # x.grad = 2 

tensor(5.)


# 2. Ví dụ 2 về Autograd cơ bản

In [7]:
# Tạo những tensors có kích thước (7, 3) và (7, 2).
x = torch.randn(10, 3)
y = torch.randn(10, 2)

In [8]:
# Tạo một tầng fully-connected
linear = nn.Linear(3, 2)
print ('w: ', linear.weight)
print ('b: ', linear.bias)

w:  Parameter containing:
tensor([[-0.5314,  0.4220,  0.1424],
        [ 0.3088, -0.0154,  0.1277]], requires_grad=True)
b:  Parameter containing:
tensor([ 0.1949, -0.5533], requires_grad=True)


In [9]:
# Tạo hàm mất mát (loss function) và bộ tối ưu hóa (optimizer)
## Hàm mất mát: MSE
## Bộ tối ưu hóa: Stochastic Gradient Descent
criterion = nn.MSELoss()
optimizer = torch.optim.SGD(linear.parameters(), lr=0.01)

In [10]:
# Lan truyền tiến (Forward pass)
pred = linear(x)

In [11]:
# Tính toán mất mát
loss = criterion(pred, y)
print('loss: ', loss.item())

loss:  1.5428675413131714


In [12]:
# Lan truyền ngược (Backward pass)
loss.backward()

In [13]:
# In ra giá trị gradient
print ('dL/dw: ', linear.weight.grad) 
print ('dL/db: ', linear.bias.grad)

dL/dw:  tensor([[-0.8683, -0.1522, -0.0204],
        [ 1.6822,  0.1952,  0.1458]])
dL/db:  tensor([ 0.1439, -0.5117])


In [14]:
# 1-step gradient descent.
optimizer.step()
# linear.weight.data.sub_(0.01 * linear.weight.grad.data)
# linear.bias.data.sub_(0.01 * linear.bias.grad.data)

In [15]:
# In ra giá trị mất mát sau một bước gradient descent.
pred = linear(x)
loss = criterion(pred, y)
print('loss after 1 step optimization: ', loss.item())

loss after 1 step optimization:  1.5038539171218872


# 3. Tải dữ liệu từ Numpy

In [16]:
# Khởi tạo một mảng Numpy (Numpy array)
x = np.array([[1, 2], [3, 4]])

In [17]:
# Chuyển đổi mảng Numpy thành Pytorch Tensor
y = torch.from_numpy(x)
print(y)
print(type(y))

tensor([[1, 2],
        [3, 4]])
<class 'torch.Tensor'>


In [18]:
# Chuyển đổi PyTorch Tensor thành Numpy array
z = y.numpy()
print(z)
print(type(z))

[[1 2]
 [3 4]]
<class 'numpy.ndarray'>


In [ ]:
# 4. Input pipline 

In [19]:
# Tải bộ dữ liệu CIFAR10
train_dataset = torchvision.datasets.CIFAR10(root='../../data/',
                                             train=True, 
                                             transform=transforms.ToTensor(),
                                             download=True)

170499072it [03:21, 846056.06it/s]                                              


Extracting ../../data/cifar-10-python.tar.gz to ../../data/


In [20]:
# Lấy ra một cặp dữ liệu (cặp đầu tiên)
image, label = train_dataset[0]
print(image.size())
print(label)

torch.Size([3, 32, 32])
6


In [21]:
# Data loader
train_loader = torch.utils.data.DataLoader(dataset=train_dataset,
                                           batch_size=64, 
                                           shuffle=True)

In [22]:
# Khi bắt đầu vòng lap57, hàng đợi và luồng bắt đầu tải dữ liệu từ tệp.
data_iter = iter(train_loader)

In [23]:
# Mini-batch images and labels.
images, labels = data_iter.next()

# Actual usage of the data loader is as below.
for images, labels in train_loader:
    # Training code should be written here.
    pass

In [ ]:
# 5. Input pipline cho bộ dữ liệu tùy chọn (custom dataset)
class CustomDataset(torch.utils.data.Dataset):
    def __init__(self):
        # TODO
        # 1. Khởi tạo đường dẫn tập tin hoặc một danh sách của những tập tin
        pass
    def __getitem__(self, index):
        # TODO
        # 1. Đọc một dữ liệu từ file (sử dụng numpy.fromfile, PIL.Image.open).
        
        # 2. Tiền xử lý dữ liệu (sử dụng torchvision.Transform).
        
        # 3. Trả về một cặp dữ liệu (ví dụ như là hình ảnh - image và nhãn - label)
        pass
    def __len__(self):
        # Thay đổi 0 thành kích thước của bộ dữ liệu
        return 0 
    
custom_dataset = CustomDataset()
train_loader = torch.utils.data.DataLoader(dataset=custom_dataset,
                                           batch_size=64, 
                                           shuffle=True)

In [25]:
# 6. Mô hình được huấn luyện từ trước (Pretrained model)
# Tải xuống và load mô hình được huấn luyện trước (Pretrained model) - ResNet18
resnet = torchvision.models.resnet18(pretrained=True)

# Nếu bạn chỉ muốn finetune lớp trên cùng của mô hình, hãy thiết lập như bên dưới.
for param in resnet.parameters():
    param.requires_grad = False
      
# Replace the top layer for finetuning.
resnet.fc = nn.Linear(resnet.fc.in_features, 100)

# Forward pass.
images = torch.randn(64, 3, 224, 224)
outputs = resnet(images)
print (outputs.size())     # (64, 100)

Downloading: "https://download.pytorch.org/models/resnet18-5c106cde.pth" to /home/lenux/.cache/torch/hub/checkpoints/resnet18-5c106cde.pth
100%|██████████████████████████████████████| 44.7M/44.7M [00:37<00:00, 1.24MB/s]


torch.Size([64, 100])


In [26]:
# 7. Lưu và tải lại mô hình (Save and load model)
#torch.save(resnet, 'model.ckpt')
#model = torch.load('model.ckpt')

# Save and load only the model parameters (recommended).
torch.save(resnet.state_dict(), 'params.ckpt')
resnet.load_state_dict(torch.load('params.ckpt'))

<All keys matched successfully>